version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/" 
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions" # update GitHub Actions workflows
    directory: "/" 
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"