name: Dotnet CI Composite
description: Composite action to run common .NET CI steps (checkout, setup, restore, build, test).
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      shell: pwsh
      run: dotnet restore

    - name: Build
      shell: pwsh
      run: dotnet build --no-restore

    - name: Test
      shell: pwsh 
      run: dotnet test --no-build --verbosity normal

inputs:
  dotnet-version:
    description: '.NET SDK version to install'
    required: false
    default: '10.0.x'
